#ifndef SEDHOM_OS_SETTINGS_H_
#define SEDHOM_OS_SETTINGS_H_
//SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
// include external libraries here
////////////////////////////////////////
#include <Arduino.h>
////////////////////////////////////////
// #include <UTFTGLUE.h>    
#include <MCUFRIEND_kbv.h>
// #include <Adafruit_TFTLCD.h>      
////////////////////////////////////////
#include <TouchScreen.h>
////////////////////////////////////////
// #include <QRCodeGFX.h>
//////////////////////////////////////
// #include <ArduinoJson.h>
//////////////////////////////////////
//SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
// objects 
MCUFRIEND_kbv Display;
//SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
//SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
//SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
#endif // !SEDHOM_OS_SETTINGS_H_