#ifndef SEDHOM_CONTROLE_H_
#define SEDHOM_CONTROLE_H_
//QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ
#include "SEDHOM_Data_Types.h"
#include "SEDHOM_Icons.h"
#include "SEDHOM_Time.h"
#include "SEDHOM_Display_Touch.h"
//QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ
//QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ
class SEDHOM_Controls
{
private:
    /* data */
public:
    SEDHOM_Controls();
    ~SEDHOM_Controls();
    // functions
     // Button
     void Button_Control();

};

SEDHOM_Controls::SEDHOM_Controls()
{
}

SEDHOM_Controls::~SEDHOM_Controls()
{
}

//QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ
//QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ
#endif // !SEDHOM_CONTROLE_H_